Add https://download.opensuse.org/repositories/openSUSE:/Factory/standard/src/python3-pynest2d-4.8.0-3.1.src.rpm.
Preparing to address cura build (test) failure
+ /usr/bin/python3 -m pytest -v
/usr/lib/python3.9/site-packages/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
ImportError while loading conftest '/builddir/build/BUILD/Cura-4.8.0/tests/conftest.py'.
tests/conftest.py:15: in <module>
    from cura.CuraApplication import CuraApplication
cura/CuraApplication.py:55: in <module>
    from cura.Arranging.ArrangeObjectsJob import ArrangeObjectsJob
cura/Arranging/ArrangeObjectsJob.py:11: in <module>
    from cura.Arranging.Nest2DArrange import arrange
cura/Arranging/Nest2DArrange.py:2: in <module>
    from pynest2d import Point, Box, Item, NfpConfig, nest
E   ModuleNotFoundError: No module named 'pynest2d'
error: Bad exit status from /var/tmp/rpm-tmp.a4Oy3t (%check)
    Bad exit status from /var/tmp/rpm-tmp.a4Oy3t (%check)